sudo: required
dist: trusty

language: java
jdk:
  - oraclejdk8
  - openjdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f $HOME/.gradle/caches/minecraft/ForgeVersion.json
  - rm -f $HOME/.gradle/caches/minecraft/ForgeVersion.json.etag
  - rm -rf $HOME/.gradle/caches/minecraft/deobfedDeps
  - rm -f $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
  - rm -f $HOME/.gradle/caches/*/fileHashes/fileHashes.lock

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle/wrapper'
    - '$HOME/.gradle/caches'

before_install:
  - chmod +x gradlew
  - ./gradlew
install:
  - ./gradlew setupCIWorkspace --stacktrace

before_script:
  - 'echo "Build-testing commit $TRAVIS_BRANCH / $TRAVIS_COMMIT"'
  - 'if [ "$TRAVIS_PULL_REQUEST" -ne "false" ]; then echo "PR being tested: $TRAVIS_PULL_REQUEST"; else echo "No PR being tested"; fi'
  - 'echo "Current build id: $TRAVIS_BUILD_ID"'
script:
  - ./gradlew build --stacktrace
  - ./gradlew check --info --stacktrace
  - ./gradlew test --stacktrace
